name: cashwalkclone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0-71.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  percent_indicator: ^4.2.2
  pedometer: ^3.0.0
  image_picker: ^0.8.6
  get_storage: ^2.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: IBMKR
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans_KR/IBMPlexSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBM_Plex_Sans_KR/IBMPlexSansKR-Regular.ttf
          weight: 300

    - family: LS
      fonts:
        - asset: assets/fonts/Lobster/Lobster-Regular.ttf
          weight: 700

